version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - PYTHONPATH=/app
    restart: always

  frontend:
    build: ./frontend/finsight-ai
    ports:
      - "3001:3000"
    restart: always
    depends_on:
      - backend
